### PR TITLE
Created initial readme

### PR DESCRIPTION
**Pull request by enarhi**
Added initial readme info.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check required

**Review by JohnSloane — APPROVED** [review]

**Comment by enarhi** [comment]
@BHoMBot check required

**Review by JohnSloane — APPROVED** [review]

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5321064320

**Pull request merged**
