### PR TITLE
Inspection_oM: Added two new properties to Issues

### LINKED ISSUE #38: Update to changes in Inspection_oM
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/BHoM/pull/1178

#### Description:
Per updated iAuditor workflow requirements, new properties have been added for AuditID and ClosedDate on issues. In addition we need to add the ability to independently pull issues and audits from iAuditor to store them separately downstream and avoid duplicate issues existing in the audit and separate from the audit.

### PR DESCRIPTION
**Pull request by enarhi**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1178

   
### Issues addressed by this PR

Closes #38 

Restructured audits and issues so they are returned independently to align with usage of issues (persistent, changed downstream) and audits (pulled once and left as is), and to align to new properties added to oM accordingly.

### Test files
Test file [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/iAuditor_Toolkit/%2339-AddedTwoNewPropertiesToIssues?csf=1&web=1&e=lSFCdn).

Pull any audit as per previous scripts and confirm audit as well as issues are returned, with the audit maintaining issue numbers but not the issues themselves.

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by tiagogrossi** [comment]
@enarhi thanks for opening this PR, I've tried to test but got some error messages. Could you please check the test file that I uploaded in the description above? It has all the necessary credentials. Am I missing something?

**Comment by enarhi** [comment]
@tiagogrossi please try now, last commit should fix your issue. I have updated your example script as well to reflect the new changes, allowing an audit and issues to be pulled separately if so desired.

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
Guys, 

BHoM/BHoM#1178 was merged without this PR. This means that the master is currently in a state that cannot compile. 

I will merge this to fix the master but you will need to review this PR properly even if I close it.

I have raised a separate issue for that: https://github.com/BHoM/iAuditor_Toolkit/issues/40

**Review by adecler — APPROVED** [review]
Approve for now based on the fact that it compiles See comment above requesting a proper review

**Pull request merged**
