### PR TITLE
Added method to get latest unique issues from list of issues

### LINKED ISSUE #44: Add method to get only the latest instance of each Issue from a Collection of Issues
#### Description:
As we are using the database as a record of all issue changes, it will include multiple instances of updated issues. This method will make it easy for us to only get the latest instance of each unique issue to send to handle for pushes, updates, etc.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #44 

This new method allows us to get the latest unique instance of each Issue from a collection of issues that includes duplicates of issues for each time it has been modified.

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/iAuditor_Toolkit/%2344-GetLatestIssues?csf=1&web=1&e=ptbxG5

### CODE REVIEW

**Review by BSochacki — DISMISSED** [review]
All looks good, tested with change pushed through. Worked as indented. 
LGTM
Small suggestion to remove unused references.

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by tiagogrossi** [comment]
@BHoMBot check dataset-compliance

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by BSochacki** [comment]
LGTM

**Review by BSochacki — APPROVED** [review]
LGTM

**Pull request merged**
