### PR TITLE
Removed unincluded and unused files

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #

removed files that were unincluded in their projects, and would have made compile errors if they were. Otherwise fixed a bunch of punctuation.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Review by FraserGreenroyd — DISMISSED** [review]
This looks good now, thanks @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 23109994337

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Still looks good, thanks @Tom-Kingstone

**Pull request merged**
